// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulse.Api.Data;

#nullable disable

namespace Pulse.Api.Migrations;

[DbContext(typeof(PulseDbContext))]
partial class PulseDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(
        ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation(
                "Relational:MaxIdentifierLength",
                63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(
            modelBuilder);

        modelBuilder.Entity(
            "Pulse.Api.Domain.Block",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions
                    .UseIdentityByDefaultColumn(
                        entity.Property<int>("Id"));

                entity.Property<int>("BlockedUserId")
                    .HasColumnType("integer");

                entity.Property<int>("BlockerId")
                    .HasColumnType("integer");

                entity.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                entity.HasKey("Id");

                entity.HasIndex("BlockedUserId");

                entity.HasIndex(
                        "BlockerId",
                        "BlockedUserId")
                    .IsUnique();

                entity.ToTable("Blocks");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Follow",
            entity =>
            {
                entity.Property<int>("FollowerId")
                    .HasColumnType("integer");

                entity.Property<int>("FollowingId")
                    .HasColumnType("integer");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                entity.HasKey(
                    "FollowerId",
                    "FollowingId");

                entity.HasIndex("FollowingId");

                entity.ToTable("Follows");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.ModerationActionRecord",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions
                    .UseIdentityByDefaultColumn(
                        entity.Property<int>("Id"));

                entity.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType(
                        "character varying(16)");

                entity.Property<DateTime>("CreatedAt")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<int>("ModeratorUserId")
                    .HasColumnType("integer");

                entity.Property<string>("Note")
                    .HasMaxLength(500)
                    .HasColumnType(
                        "character varying(500)");

                entity.Property<int>("ReportId")
                    .HasColumnType("integer");

                entity.HasKey("Id");

                entity.HasIndex("ModeratorUserId");

                entity.HasIndex("ReportId");

                entity.ToTable("ModerationActions");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Post",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions
                    .UseIdentityByDefaultColumn(
                        entity.Property<int>("Id"));

                entity.Property<int>("AuthorId")
                    .HasColumnType("integer");

                entity.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(280)
                    .HasColumnType(
                        "character varying(280)");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<DateTime?>("DeletedAt")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<int?>("ParentPostId")
                    .HasColumnType("integer");

                entity.HasKey("Id");

                entity.HasIndex("AuthorId");

                entity.HasIndex("CreatedAtUtc");

                entity.HasIndex("ParentPostId");

                entity.ToTable("Posts");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.PostLike",
            entity =>
            {
                entity.Property<int>("PostId")
                    .HasColumnType("integer");

                entity.Property<int>("UserId")
                    .HasColumnType("integer");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.HasKey(
                    "PostId",
                    "UserId");

                entity.HasIndex("UserId");

                entity.ToTable("PostLikes");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Report",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions
                    .UseIdentityByDefaultColumn(
                        entity.Property<int>("Id"));

                entity.Property<DateTime>("CreatedAt")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<string>("Details")
                    .HasMaxLength(500)
                    .HasColumnType(
                        "character varying(500)");

                entity.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType(
                        "character varying(32)");

                entity.Property<int>("ReporterId")
                    .HasColumnType("integer");

                entity.Property<DateTime?>("ReviewedAt")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<int?>("ReviewedByUserId")
                    .HasColumnType("integer");

                entity.Property<string>("Status")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(16)
                    .HasColumnType(
                        "character varying(16)")
                    .HasDefaultValue("Pending");

                entity.Property<int>("TargetId")
                    .HasColumnType("integer");

                entity.Property<string>("TargetType")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType(
                        "character varying(16)");

                entity.HasKey("Id");

                entity.HasIndex(
                    "ReporterId",
                    "TargetType",
                    "TargetId");

                entity.HasIndex("ReviewedByUserId");

                entity.HasIndex(
                    "Status",
                    "CreatedAt");

                entity.HasIndex(
                    "TargetType",
                    "TargetId");

                entity.ToTable("Reports");
            });
        modelBuilder.Entity(
            "Pulse.Api.Domain.User",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions
                    .UseIdentityByDefaultColumn(
                        entity.Property<int>("Id"));

                entity.Property<string>("AvatarUrl")
                    .HasMaxLength(2048)
                    .HasColumnType(
                        "character varying(2048)");

                entity.Property<string>("Bio")
                    .HasMaxLength(160)
                    .HasColumnType(
                        "character varying(160)");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType(
                        "timestamp with time zone");

                entity.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType(
                        "character varying(80)");

                entity.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType(
                        "character varying(254)");

                entity.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                entity.Property<string>("NormalizedEmail")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType(
                        "character varying(254)");

                entity.Property<string>("NormalizedUsername")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType(
                        "character varying(30)");

                entity.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType(
                        "character varying(512)");

                entity.Property<string>("Role")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(32)
                    .HasColumnType(
                        "character varying(32)")
                    .HasDefaultValue("user");

                entity.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType(
                        "character varying(30)");

                entity.HasKey("Id");

                entity.HasIndex(
                    "IsActive",
                    "CreatedAtUtc");

                entity.HasIndex("NormalizedEmail")
                    .IsUnique();

                entity.HasIndex("NormalizedUsername")
                    .IsUnique();

                entity.ToTable("Users");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Block",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "BlockedUser")
                    .WithMany("BlocksReceived")
                    .HasForeignKey("BlockedUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "Blocker")
                    .WithMany("BlocksCreated")
                    .HasForeignKey("BlockerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.Navigation("BlockedUser");

                entity.Navigation("Blocker");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Follow",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "Follower")
                    .WithMany("Following")
                    .HasForeignKey("FollowerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "FollowingUser")
                    .WithMany("Followers")
                    .HasForeignKey("FollowingId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.Navigation("Follower");

                entity.Navigation("FollowingUser");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.ModerationActionRecord",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "ModeratorUser")
                    .WithMany("ModerationActions")
                    .HasForeignKey("ModeratorUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.Report",
                        "Report")
                    .WithMany("ModerationActions")
                    .HasForeignKey("ReportId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.Navigation("ModeratorUser");

                entity.Navigation("Report");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Post",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "Author")
                    .WithMany("Posts")
                    .HasForeignKey("AuthorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.Post",
                        "ParentPost")
                    .WithMany("Replies")
                    .HasForeignKey("ParentPostId")
                    .OnDelete(DeleteBehavior.Restrict);

                entity.Navigation("Author");

                entity.Navigation("ParentPost");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.PostLike",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.Post",
                        "Post")
                    .WithMany("Likes")
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "User")
                    .WithMany("PostLikes")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.Navigation("Post");

                entity.Navigation("User");
            });
        modelBuilder.Entity(
            "Pulse.Api.Domain.Report",
            entity =>
            {
                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "Reporter")
                    .WithMany("ReportsCreated")
                    .HasForeignKey("ReporterId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.HasOne(
                        "Pulse.Api.Domain.User",
                        "ReviewedByUser")
                    .WithMany("ReportsReviewed")
                    .HasForeignKey("ReviewedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                entity.Navigation("Reporter");

                entity.Navigation("ReviewedByUser");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Post",
            entity =>
            {
                entity.Navigation("Likes");

                entity.Navigation("Replies");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.Report",
            entity =>
            {
                entity.Navigation("ModerationActions");
            });

        modelBuilder.Entity(
            "Pulse.Api.Domain.User",
            entity =>
            {
                entity.Navigation("BlocksCreated");

                entity.Navigation("BlocksReceived");

                entity.Navigation("Followers");

                entity.Navigation("Following");

                entity.Navigation("ModerationActions");

                entity.Navigation("PostLikes");

                entity.Navigation("Posts");

                entity.Navigation("ReportsCreated");

                entity.Navigation("ReportsReviewed");
            });
#pragma warning restore 612, 618
    }
}